import Footer from '#/shared/Footer';
import Header from '#/shared/Header';
import Providers from '@/components/Providers';
import { gmarketSans } from '@/styles/fonts';
import '@/styles/globals.css';
import { cn } from '@/utils/styles';
import Head from 'next/head';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'relative flex size-full flex-col font-gmarket',
          gmarketSans.variable
        )}
      >
        <Providers>
          <Head>
            <link
              rel="icon"
              href="../../public/favicon.svg"
              type="image/svg+xml"
            />
          </Head>
          <div
            className={cn(
              'flex h-screen w-screen flex-col items-center text-sm lg:text-base'
            )}
          >
            <Header />
            <main className="relative flex size-full flex-1 items-center justify-center overflow-auto">
              {children}
            </main>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
